version: '3.8'

services:
  # Web服务
  nginx:
    container_name: articles_nginx
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html:ro
    depends_on:
      - php
     # php:
      #  condition: service_healthy
    networks:
      - lnmp-net

  # PHP处理
  php:
    container_name: articles_php
    build: ./php
    image: my_articles_php-8.2
    volumes:
      - ./html:/var/www/html
    environment:
      - TZ=Asia/Shanghai
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lnmp-net

  # 数据库
  mysql:
    container_name: article_mysql
    image: mysql:8.0-debian
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # 挂载初始化脚本目录（容器会自动执行该目录下的.sql文件）
      - ./mysql/init:/docker-entrypoint-initdb.d
             
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - lnmp-net


 #Redis缓存服务
  redis:
    container_name: articles_redis
    image: redis:7.2-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lnmp-net

volumes:
  mysql_data:
  redis_data:

networks:
  lnmp-net:
    driver: bridge
